export const adjectives = [
  'Swift', 'Bold', 'Brave', 'Clever', 'Cunning', 'Daring', 'Fierce', 'Silent',
  'Mighty', 'Noble', 'Quick', 'Wise', 'Ancient', 'Blazing', 'Crimson', 'Dark',
  'Electric', 'Frozen', 'Golden', 'Hidden', 'Iron', 'Jade', 'Keen', 'Lunar',
  'Mystic', 'Night', 'Ocean', 'Phantom', 'Quiet', 'Rapid', 'Shadow', 'Thunder',
  'Valiant', 'Wild', 'Azure', 'Bright', 'Cosmic', 'Deep', 'Emerald', 'Flaming',
  'Gentle', 'Heavy', 'Icy', 'Jolly', 'Kind', 'Lucky', 'Marble', 'Nimble',
  'Orange', 'Pink', 'Royal', 'Scarlet', 'Tidal', 'Violet', 'White', 'Yellow',
  'Amber', 'Black', 'Copper', 'Diamond', 'Ebony', 'Frosty', 'Gray', 'Indigo',
  'Jade', 'Keen', 'Lemon', 'Magenta', 'Navy', 'Olive', 'Pearl', 'Quartz',
  'Ruby', 'Silver', 'Topaz', 'Ultra', 'Vivid', 'Warm', 'Zesty', 'Agile',
  'Blunt', 'Cold', 'Dense', 'Eager', 'Faint', 'Giant', 'Harsh', 'Ideal',
  'Jumbo', 'Known', 'Large', 'Minor', 'Neat', 'Odd', 'Plain', 'Rare',
  'Sharp', 'Tall', 'Unique', 'Vast', 'Weak', 'Young', 'Calm', 'Dusty',
  'Epic', 'Fair', 'Grim', 'Holy', 'Idle', 'Just', 'Lone', 'Mere',
  'Pure', 'Rich', 'Safe', 'True', 'Vain', 'Wary', 'Apt', 'Avid',
  'Busy', 'Cool', 'Dry', 'Easy', 'Fast', 'Fine', 'Fond', 'Free',
  'Full', 'Good', 'High', 'Hot', 'Huge', 'Kind', 'Last', 'Late',
  'Lazy', 'Long', 'Lost', 'Loud', 'Low', 'Mad', 'Main', 'Mean',
  'Mild', 'New', 'Next', 'Nice', 'Odd', 'Old', 'Only', 'Open',
  'Pale', 'Past', 'Poor', 'Real', 'Rear', 'Red', 'Rude', 'Sad',
  'Sly', 'Slow', 'Soft', 'Sole', 'Sour', 'Tame', 'Tiny', 'Ugly',
  'Vague', 'Warm', 'Wavy', 'Weak', 'Wide', 'Wild', 'Wise', 'Zero'
];
