export const nouns = [
  'Warrior', 'Ranger', 'Knight', 'Mage', 'Rogue', 'Paladin', 'Hunter', 'Druid',
  'Wizard', 'Sorcerer', 'Monk', 'Barbarian', 'Bard', 'Cleric', 'Warlock', 'Shaman',
  'Archer', 'Fighter', 'Guardian', 'Champion', 'Hero', 'Legend', 'Master', 'Sage',
  'Tiger', 'Wolf', 'Bear', 'Eagle', 'Dragon', 'Phoenix', 'Lion', 'Hawk',
  'Falcon', 'Raven', 'Shark', 'Panther', 'Cobra', 'Viper', 'Lynx', 'Otter',
  'Fox', 'Owl', 'Crane', 'Mantis', 'Scorpion', 'Spider', 'Wasp', 'Hornet',
  'Storm', 'Thunder', 'Lightning', 'Tornado', 'Hurricane', 'Blizzard', 'Tempest', 'Cyclone',
  'Mountain', 'Valley', 'River', 'Ocean', 'Forest', 'Desert', 'Tundra', 'Glacier',
  'Volcano', 'Canyon', 'Cliff', 'Peak', 'Summit', 'Ridge', 'Crest', 'Hollow',
  'Blade', 'Sword', 'Axe', 'Hammer', 'Spear', 'Bow', 'Arrow', 'Shield',
  'Staff', 'Wand', 'Dagger', 'Mace', 'Flail', 'Lance', 'Javelin', 'Saber',
  'Star', 'Moon', 'Sun', 'Comet', 'Nova', 'Eclipse', 'Aurora', 'Nebula',
  'Planet', 'Meteor', 'Asteroid', 'Galaxy', 'Cosmos', 'Void', 'Abyss', 'Nexus',
  'Shadow', 'Phantom', 'Ghost', 'Specter', 'Wraith', 'Spirit', 'Soul', 'Essence',
  'Flame', 'Inferno', 'Ember', 'Blaze', 'Spark', 'Fire', 'Ash', 'Coal',
  'Ice', 'Frost', 'Snow', 'Hail', 'Crystal', 'Diamond', 'Sapphire', 'Ruby',
  'Emerald', 'Jade', 'Opal', 'Pearl', 'Topaz', 'Amber', 'Quartz', 'Onyx',
  'Steel', 'Iron', 'Bronze', 'Copper', 'Silver', 'Gold', 'Platinum', 'Titanium',
  'Rock', 'Stone', 'Boulder', 'Granite', 'Marble', 'Obsidian', 'Flint', 'Slate',
  'Wind', 'Breeze', 'Gale', 'Zephyr', 'Draft', 'Gust', 'Squall', 'Whirlwind',
  'Wave', 'Tide', 'Current', 'Stream', 'Rapids', 'Cascade', 'Falls', 'Torrent',
  'Cloud', 'Mist', 'Fog', 'Haze', 'Vapor', 'Smoke', 'Steam', 'Rain',
  'Dawn', 'Dusk', 'Twilight', 'Noon', 'Midnight', 'Morning', 'Evening', 'Night',
  'Spring', 'Summer', 'Autumn', 'Winter', 'Season', 'Equinox', 'Solstice', 'Eclipse',
  'Crown', 'Throne', 'Scepter', 'Orb', 'Ring', 'Amulet', 'Talisman', 'Charm'
];
